name: homestead
favicon: null
layout_spectrum: 0.94676
typography_spectrum: 0.9666266883723438
title: Sand Castles
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d4d63'
    - '#8590b0'
    - '#b7cfdb'
    - '#07281f'
    - '#5e4a89'
  brandStrength: 0.10084340651519597
  lightness: 0.5
  saturation: 0.9790217904374003
  rhythmicContrast: 0.822831753641367
purpose: []
