typography_spectrum: 0.08566932054236531
color:
  brandColors:
    - '#36362C'
    - '#5D917D'
    - '#A8AD80'
    - '#E6D4A7'
    - '#825534'
  brandStrength: 0.5511645015794784
  lightness: 0.48740102304145694
  saturation: 0.9058510239701718
  rhythmicContrast: 0.3934615864418447
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.18220102414488792
analytics:
  google: 777426661265-obabyMYoMY
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/043c81e4-58e6-4220-9540-9d055e3a2adb.jpg
name: homestead
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Sand Castles
description: Where the ephemeral world builds it's skyscrapers and monuments
purpose: []
