name: homestead
favicon: null
layout_spectrum: 0.3742
typography_spectrum: 0.88953
title: Sand Castles
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d4d63'
    - '#8590b0'
    - '#b7cfdb'
    - '#07281f'
    - '#5e4a89'
  brandStrength: 0.1875
  lightness: 0.5625
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
