name: homestead
favicon: null
layout_spectrum: 0
typography_spectrum: 0.11974
title: Sand Castles
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: 777426661265-obabyMYoMY
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d4d63'
    - '#8590b0'
    - '#b7cfdb'
    - '#07281f'
    - '#5e4a89'
  brandStrength: 0.125
  lightness: 0
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
