typography_spectrum: 0.4008538965135813
color:
  brandColors:
    - '#1d4d63'
    - '#8590b0'
    - '#b7cfdb'
    - '#07281f'
    - '#5e4a89'
  brandStrength: 0.125
  lightness: 0
  saturation: 0.5625
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3070587939582765
analytics:
  google: 777426661265-obabyMYoMY
  facebook: null
  twitter: null
name: homestead
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Sand Castles
description: Where the ephemeral world builds it's skyscrapers and monuments
purpose: []
